### ISSUE TITLE
Quick question....

### ISSUE THREAD

**Issue by austrocoin** [amosbastian/steempy-tutorials#1]
How would the trailbot (#4) look when want to limit the trailing on predefined tags (so it only follow with vote on posts when this have tags what are predefined)? Somehow I dont get it - lol. Thanks for a quick hint :)

**Comment by amosbastian** [comment]
You would have to get the tags of each post and check if your tag is in there, so for example:

```
tag = "utopian-io"
if voter in voting_trail:
    post = template.format(author, permlink)
    tags = post["tags"]
    if Post(post).is_main_post() and tag in tags:
        # DO SOMETHING
```
